# Generated by Django 5.0.3 on 2024-04-03 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the shop.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the shop.', null=True)),
                ('image_url', models.ImageField(blank=True, help_text='Image of the shop.', null=True, upload_to='shop/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the category.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ManyToManyField(to='MahsulotCom.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the product.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the product.', null=True)),
                ('amount', models.PositiveIntegerField(blank=True, help_text='The amount of the product.', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='The price of the product.', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of the product.', null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('active', models.BooleanField(default=True, help_text='Activate the product.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ManyToManyField(related_name='products', to='MahsulotCom.category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='MahsulotCom.shop')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
