# Generated by Django 5.0.3 on 2024-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahsulotCom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_id', to='MahsulotCom.category'),
        ),
    ]
